package com.msb.bpm.approval.appr.enums.card;

import lombok.Getter;

@Getter
public enum IntegrationResponseCode {
  SUCCESSFUL(0),
  DATA_INVALID(400),
  REQUEST_TIMEOUT(408),
  CIF_NOT_FOUND(2008),
  CLIENT_INFO_INVALID(2014),
  CLIENT_IS_EXIST(2022),
  CLIENT_INACTIVE(2023),
  CREATE_CLIENT_FAIL(2024),
  CANNOT_CREATE_LIABILITY_CONTRACT(2009),
  CANNOT_SET_CREDIT_LIMIT_FOR_CONTRACT(2010),
  CREATE_CONTRACT_ADDRESS_FAIL(2011),
  CONTRACT_NUMBER_NOT_FOUND(2013),
  RBS_NUMBER_NOT_MATCH(2014),
  CIF_ALREADY_HAD_LIABILITY(2021),
  USER_INFO_FROM_CORE_NOT_HAVE_EMAIL(3004),
  USER_INFO_FROM_CORE_NOT_HAVE_PHONE(3003),
  CLIENT_IS_EXIST_BUT_NOT_READY(2036),
  EDIT_CLIENT_FAIL(2039),
  REGNUMBER_NOT_MATCH_WITH_WAY4(2064),
  TIMEOUT(504),
  BAD_REQUEST(400),
  REGNUMBER_IS_EXISTS_IN_WAY4(2065),
  REGNUMBER_NOT_MATCH_WITH_CORE(3005);
  private Integer code;

  IntegrationResponseCode(Integer code) {
    this.code = code;
  }
}
