@startuml
skin rose
participant RM
participant RB_APPROVAL_FE
participant RB_APPROVAL_BE

RM -> RB_APPROVAL_FE: choose application
RB_APPROVAL_FE -> RB_APPROVAL_FE: display detail application
RM -> RB_APPROVAL_FE: choose file checklist
RM -> RB_APPROVAL_FE: preview checklist
alt valid
    RB_APPROVAL_FE -> RB_APPROVAL_BE: call api "/api/v1/checklist/file/pre-signed-download"
    RB_APPROVAL_BE --> RB_APPROVAL_FE: return (filePath && url && bucket)
else invalid
    RB_APPROVAL_BE --> RB_APPROVAL_FE: return error code
end
@enduml
